### PR TITLE
Internal fixes

### PR DESCRIPTION
**Pull request by IanEisenberg**

### CODE REVIEW

**Comment by vsoch** [comment]
Why are all these commits still here from 11 days ago? Did you rebase with master?

**Comment by IanEisenberg** [comment]
Not sure. I rebased, not sure why new PRs show all these old commits. Only 78252c8 is new.

**Comment by vsoch** [comment]
What you want to do is start from master, check out a new branch, and then make the small changes. You can make a new PR if needed! Not sure why it's coming through like this, but best to have it clean. What I would do generally in the future is to just have specific branches for different PRs, and delete them when you merge, and always check out a new branch from master, makes it easier to avoid strange things like this.

**Comment by IanEisenberg** [comment]
Yep, I'll do that.

On Thu, May 19, 2016 at 10:36 AM, Vanessa Sochat <notifications@github.com>
wrote:

> What you want to do is start from master, check out a new branch, and then
> make the small changes. You can make a new PR if needed! Not sure why it's
> coming through like this, but best to have it clean. What I would do
> generally in the future is to just have specific branches for different
> PRs, and delete them when you merge, and always check out a new branch from
> master, makes it easier to avoid strange things like this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/pull/452#issuecomment-220397337>
>



-- 
Best,
Ian

**Pull request closed without merging**
