### PR TITLE
Rig cct

### PR DESCRIPTION
**Pull request by IanEisenberg**

### CODE REVIEW

**Comment by IanEisenberg** [comment]
Don't merge this quite yet.

**Comment by vsoch** [comment]
Ready for merge?

**Comment by IanEisenberg** [comment]
Not yet!

On Wed, Jun 22, 2016 at 1:53 PM, Vanessa Sochat <notifications@github.com>
wrote:

> Ready for merge?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/pull/471#issuecomment-227873001>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AI5LgEfPdEN7eXE46ol3YUhiUmdQ4WXgks5qOaDEgaJpZM4I7X08>
> .
>



-- 
Best,
Ian

**Comment by vsoch** [comment]
or this one first?

**Comment by IanEisenberg** [comment]
Either one. I'll rebase the other one.

On Wednesday, June 29, 2016, Vanessa Sochat <notifications@github.com>
wrote:

> or this one first?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/pull/471#issuecomment-229444538>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AI5LgI2F-hTw_M0M1Wbwf3BshzYJ7H-uks5qQrhFgaJpZM4I7X08>
> .
>


-- 
Best,
Ian

**Pull request merged**
