### PR TITLE
Fix pr313

### PR DESCRIPTION
**Pull request by IanEisenberg**

### CODE REVIEW

**Comment by vsoch** [comment]
the dot_pattern_expectancy error isn't triggering a 404 because the errors are generated with the preload - specifically the image paths are trying to be preloaded at the root (where they don't exist). I had created an issue for this #320

**Comment by IanEisenberg** [comment]
I've fixed that error, but it doesn't seem to lead to a 'failure' of this
PR, so I'll repair it after merging. This PR has a bunch of things that
need to be merged, and I'm tired of waiting for testing of every single
component on each rebuild.

On Mon, Feb 29, 2016 at 2:03 PM, Vanessa Sochat <notifications@github.com>
wrote:

> the dot_pattern_expectancy error isn't triggering a 404 because the errors
> are generated with the preload - specifically the image paths are trying to
> be preloaded at the root (where they don't exist). I had created an issue
> for this #320
> <https://github.com/expfactory/expfactory-experiments/issues/320>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/pull/318#issuecomment-190417360>
> .
>



-- 
Best,
Ian

**Comment by vsoch** [comment]
Chris gave me this advice a while back, it's a good idea to do many small PRs than one large one.

**Comment by IanEisenberg** [comment]
Ya. This one has gotten too big :)

On Monday, February 29, 2016, Vanessa Sochat <notifications@github.com>
wrote:

> Chris gave me this advice a while back, it's a good idea to do many small
> PRs than one large one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/pull/318#issuecomment-190429201>
> .
>


-- 
Best,
Ian

**Comment by vsoch** [comment]
I know the bug for recent_probes... if everything else is good we can merge and I'll fix it right away.

**Comment by IanEisenberg** [comment]
Oh good. I don't know that bug. I think it's the same as multiplication? Could you explain it to me after the rest finishes?

**Comment by vsoch** [comment]
yep, the same. It's just a value given as a list, eg

      [1700]

when it needs to be numeric:

      1700

**Comment by IanEisenberg** [comment]
Cool, got it. I'll send that in right before I merge

**Pull request merged**
