### PR TITLE
Issues presented on github

### PR DESCRIPTION
**Pull request by jkl071**

### CODE REVIEW

**Comment by vsoch** [comment]
What does "gm" mean?

**Comment by jkl071** [comment]
Hi Vanessa, it's the circle fixes I make to gm_paradigm experiment

**Comment by vsoch** [comment]
ok cool, I wasn't sure. If there is a chance you would need to come back and find a specific commit you made, it might be a good idea to write more specific changes that you made in the commits, like:

      gm: fixed bug with performance variable

or that sort of thing. I say this from personal experience - times when I've needed to go back to something months later, and could only find it based on commit messages, it's always a big "phew!"

**Comment by vsoch** [comment]
Please rebase and merge conflicts.

**Pull request merged**
