### PR TITLE
Isi

### PR DESCRIPTION
**Pull request by IanEisenberg**

### CODE REVIEW

**Comment by vsoch** [comment]
When I do this task, one of the early page is just totally blank.

**Comment by vsoch** [comment]
Right after ending the instructions:

image

**Comment by vsoch** [comment]
Did you see this error?

      No plugin loaded for trials of type "single-stim-button"

**Comment by IanEisenberg** [comment]
I don't see that error. The experiment works fine for me when I preview in chrome or firefox, but expfactory --test does end up with a blank screen after the robot responds on the first test trial. No idea why.

**Comment by vsoch** [comment]
ok, good to merge! Great job debugging this one!

**Pull request merged**
