### PR TITLE
cue controls

### PR DESCRIPTION
**Pull request by jkl071**

### CODE REVIEW

**Comment by rwblair** [comment]
@jkl071 Looks like I don't have write access anymore.

**Comment by vsoch** [comment]
I'll fix that!

**Comment by jkl071** [comment]
Sure, feel free to add to the new expfactory-experiments.  Thanks Vanessa!

As for the container, I have a bunch of stuff that I have to do
immediately, but would be happy to follow documentation on seeing how that
works!

Thanks again for your help.

Best,
Jamie

**Comment by vsoch** [comment]
Always a pleasure! I'll test it out soon :)

**Comment by vsoch** [comment]
Quick question - the dependency `js/jspsych/poldrack_plugins/poldrack_fmri_utils.js` isn't included in your repository, or for the expfactory-battery, and I didn't see it in expfactory-docker either. Was this manually uploaded to the server? If yes, it might be worth putting under version control somewhere so the server / experiment is reproducible? And please share with me so I can add to the experiment container! :)

**Comment by rwblair** [comment]
@jkl071 I was wrong about the tests:

https://circleci.com/gh/expfactory/expfactory-experiments/1096

Didn't see the circle tests running from within github, but they are still running.

**Comment by vsoch** [comment]
eek! If it helps, the robot builder that I am serving with the modular repo runs the tests (in isolated). After previewing the experiment I'm guessing that this experiment is intended to be run on a screen in the fmri? And hence the "mri_utils" script? And the first slide that says "Press Thumb?" 

If the Thumb is mapped to a particular key it should still be testable by the robot though - if you can send me the poldrack_mri_utils.js file I'll be glad to set this up.

**Comment by vsoch** [comment]
I'm surprised the tests are still running too - Circle CI 1.0 was supposed to sunset at the end of August.

**Comment by vsoch** [comment]
okey doke, I have a repo here --> https://github.com/expfactory-experiments/cue-control-food with preview at Github pages, the testing bot is running here --> https://circleci.com/gh/expfactory-experiments/cue-control-food/9 and I'll check on him later !  When you can get me the poldrack_mri_utils.js file, and then the robot passes tests, and merging will push the finished experiment container to --> https://hub.docker.com/r/expfactory/cue-control-food/. I'll add you guys to the repo and you can send me the missing js file however you prefer! When the testing / deploy is done I'll update the README with some instructions for you to test. It will be fun! :O)

**Comment by jkl071** [comment]
Hey Vanessa,

Sorry about the super late reply, but if you're waiting on the
fmri_utils.js file for the new version of expfactory, it is no longer
required.  I've edited the discount_fix task to be a local task, instead of
an MRI task.

Thanks!

Best,
Jamie

**Comment by vsoch** [comment]
sweet! I think I was looking at cue control food, is that one changed to? If not, would you like a container for some other subset of tasks (some set of discount_* ones?)

And never apologize for taking the time to do what you need to do. You are working hard, this is mostly fun, nothing to apologize about! :muscle:

**Pull request merged**
