### PR TITLE
allowed people to advance passed test feedback

### PR DESCRIPTION
**Pull request by IanEisenberg**

### CODE REVIEW

**Comment by vsoch** [comment]
Why is there no testing?

**Comment by vsoch** [comment]
looks like Circle is offline:

image

They are updating something - we can retest when it comes back on.

**Comment by IanEisenberg** [comment]
Yeah, I saw that. Just waiting, hopefully it'll be back up soon.

**Comment by IanEisenberg** [comment]
This is also ready to be merged.

**Pull request merged**
