### PR TITLE
Util rewrite

### PR DESCRIPTION
**Pull request by IanEisenberg**

### CODE REVIEW

**Comment by vsoch** [comment]
ok, so we are removing multiplication and tone_monitoring entirely? Were they not suitable experiments?

**Comment by IanEisenberg** [comment]
They are not polished and may actually be broken. I am moving them to a
separate PR so they can be worked on and not corrupt our "prime time"
experiments.

On Wed, Apr 13, 2016 at 5:27 PM, Vanessa Sochat <notifications@github.com>
wrote:

> ok, so we are removing multiplication and tone_monitoring entirely? Were
> they not suitable experiments?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/pull/430#issuecomment-209700254>
>



-- 
Best,
Ian

**Comment by vsoch** [comment]
the rest looks good - I checked to see that the config.json and experiment.js had the exp_id added for each one, and that it matched the correct id.

Haha, sounds good. Prime time! :)

**Comment by vsoch** [comment]
My favorite experiment is still tower_of_london :) It's actually quite fun!

**Pull request merged**
