### PR TITLE
Fixes

### LINKED ISSUE #173: Shift_Task 1
The blue next button is superimposed on the rightmost shape: 
screen shot 2016-02-07 at 1 23 17 pm

This issue persists if I remove the dev tools.

### LINKED ISSUE #174: Shift_Task 2
In the instructions, it says the task is long (~20 minutes). Though this is longer than many tasks, there are severals others that are approximately this duration without a prompt that it is "fairly long". I think we should either instructs subjects on the expected duration on all tasks or none. Since we usually don't instruct them, perhaps we should never instruct them on duration.

### LINKED ISSUE #175: Shift_Task 3
Having 4 prolonged practice blocks seemed excessive. I would recommend reducing it to 3 (1 block for each feature category.

### LINKED ISSUE #177: Two Stage Decision 1
screen shot 2016-02-07 at 2 12 28 pm

Instruction images not loading. This issue was also present in the practice:

screen shot 2016-02-08 at 12 33 08 pm

And the main task: 

screen shot 2016-02-08 at 12 33 58 pm

### LINKED ISSUE #178: Two Stage Decision 2
screen shot 2016-02-07 at 2 17 01 pm

"only sometimes" seems underspecified. I think we mean "seldom".

### LINKED ISSUE #179: Two Stage Decision 3
screen shot 2016-02-08 at 12 27 29 pm

We should probably say "...won or not" not "won or lost" considering a failure to win a gold coin is not really a loss.

### LINKED ISSUE #183: Emotion Regulation 1
The instruction screen had no text: 
screen shot 2016-02-08 at 12 43 27 pm

### LINKED ISSUE #196: adaptive_n_back 2
I would recommend increasing the size of the letters, perhaps to be about twice the current height/width.

### PR DESCRIPTION
**Pull request by IanEisenberg**
fixes #175
fixes #174 
fixes #173 
fixes #196 
ignore #195 
fixes #178 
fixes #179 
fixes #183 
fixes #177

### CODE REVIEW

**Comment by vsoch** [comment]
If the poldrack-single-stim (or multi stim) plugin has not been fixed and pushed to the battery, for tasks requiring it, the robot might run forever (and hit the two hour limit). If this should not be an issue, please let me know so I can manually test why the robot is not able to take the task.

**Comment by IanEisenberg** [comment]
Good to know. Does the robot only test newly updated tasks?

On Tuesday, February 9, 2016, Vanessa Sochat <notifications@github.com>
wrote:

> If the poldrack-single-stim (or multi stim) plugin has not been fixed and
> pushed to the battery, for tasks requiring it, the robot might run forever
> (and hit the two hour limit). If this should not be an issue, please let me
> know so I can manually test why the robot is not able to take the task.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/pull/201#issuecomment-182002119>
> .
>


-- 
Best,
Ian

**Comment by vsoch** [comment]
Correct, based on a comparison between the changed files of this PR and the master branch.

**Comment by vsoch** [comment]
image

**Pull request merged**
