### PR TITLE
changed experiments beginning with a, s, t, v, and w so they work wit…

### PR DESCRIPTION
**Pull request by IanEisenberg**
…h poldrack utils

### CODE REVIEW

**Comment by IanEisenberg** [comment]
Cancelling build - failed because exp_id is not defined in the experiments (it is instead defined by a function). Adding exp_id to end_block in each experiment - both to pass validation and to ensure that one row of the data has the exp_id independent of the addID function

**Comment by IanEisenberg** [comment]
@vsoch, is there any difference between circle testing and expfactory --test? Each task is timing out on circle and passing expfactory --test no problem.

**Comment by vsoch** [comment]
when you do `expfactory --test` it runs the function [test experiment](https://github.com/expfactory/expfactory-python/blob/master/expfactory/tests.py#L516) directly. On Circle we run [circle_ci_test](https://github.com/expfactory/expfactory-python/blob/master/expfactory/tests.py#L169) which first looks for the changed experiments, and then runs [experiment_robot_web](https://github.com/expfactory/expfactory-python/blob/master/expfactory/tests.py#L295) which does the same functionality as test_experiment, but using a virtual browser controller called selenium.  Both use the exact same function, [test_block](https://github.com/expfactory/expfactory-python/blob/master/expfactory/tests.py#L356), and the only difference is one is a virtual browser (selenium on circle) and one is the browser on your computer.

**Comment by IanEisenberg** [comment]
So the timing out issue may be due to the type of browser being used? Selenium hanging in comparison to firefox?

**Comment by vsoch** [comment]
If the tests for the experiments were not timing out before, logically it has to do with some change that you made to the experiments or the battery that is not being caught. I would run the experiment_robot_web manually on your computer, using the same functions to generate the folders and such to take a look.

**Comment by vsoch** [comment]
I think the best thing to do (what I have done in the past to debug the robot) is to run the experiment_robot_web exactly as it is done on circle, one line at a time in a console, and watching the robot progress. I can tell you with almost certainty you will hit something that makes him cycle (and thus the task timing out) that you aren't detecting when you just run expfactory --test.

**Comment by vsoch** [comment]
A good standard is to directly test these things to find the error, because speculating and talking about it doesn't give confirmation of anything. Let me know if you have questions.

**Comment by IanEisenberg** [comment]
Will do

On Tue, Apr 12, 2016 at 5:33 PM, Vanessa Sochat <notifications@github.com>
wrote:

> I think the best thing to do (what I have done in the past to debug the
> robot) is to run the experiment_robot_web exactly as it is done on circle,
> one line at a time in a console, and watching the robot progress. I can
> tell you with almost certainty you will hit something that makes him cycle
> (and thus the task timing out) that you aren't detecting when you just run
> expfactory --test.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-experiments/pull/421#issuecomment-209165025>
>



-- 
Best,
Ian

**Pull request merged**
